### ISSUE TITLE
Morning Session |  Peer Programming Review

### ISSUE THREAD

**Issue by harlexkhal** [saied2035/mobile-version-skeleton#8]
### Restructuring of your projects

- Make a seperate folder for your assets like images. would help to keep the structure of your project more organised.
- Add this to your header so your font style looks exactly like whats in the figma design
 ```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
```

**Comment by mnekx** [comment]
## Transitions
-transitions are good so far 👍  but consider the below image

![image](https://user-images.githubusercontent.com/22321030/149888853-b19b808e-f170-4fd2-87be-57ba5c0f2402.png)

this could be better if text not move inside p tag when transitioning since it disturbs the eye.  the height property could be added to the transition properties.

**Comment by Bavon101** [comment]
Hello @saied2035 

- [x] Do you think your social button links would pose a better experience if all of them redirect the user to a valid social profile? I think this will make your portfolio more professional.
![social_buttons](https://user-images.githubusercontent.com/47344665/149889472-36662857-14e1-4952-bdf7-ab56855a26f9.PNG)

**Comment by saied2035** [comment]
thank you everyone I will consider that. I will make these changes as soon as possible.
